### ISSUE TITLE
configure: don't execute MPI programs

### ISSUE THREAD

**Issue by devreal** [bsc-pm/tampi#2]
The `configure` script tries to execute an MPI application to see whether the MPI implementation provides `MPI_THREAD_MULTIPLE`. Unfortunately, this leads to problems in a) cross-compile environments; and b) environments where running MPI jobs on the head nodes is disallowed. Both is true for Cray systems for example (at least with Cray MPICH and the Cray compiler wrappers). IMO, this check should be done at runtime as the chance of encountering an MPI implementation that does not provide `MPI_THREAD_MULTIPLE` is low and the overhead of checking this at runtime is negligible.

**Comment by devreal** [comment]
Ahh, I just found this `configure` flag after going through the m4 code:

```
  --disable-mpi-mt-check  Adds compiler debug flags and enables additional
                          internal debugging mechanisms [default=enabled]
```

I think the description is incorrect there. I still maintain that this check is unnecessary at compile time...

**Comment by kevinsala** [comment]
We have removed the MPI multi-threading check and its option from the configuration process in master.

Thank you for reporting.
