### ISSUE TITLE
TAMPI_Iwaitall Assertion `!requests.empty()' fails when count=0 and reqs={MPI_REQUEST_NULL}

### ISSUE THREAD

**Issue by dsloanm-epcc** [bsc-pm/tampi#3]
The `TAMPI_Iwaitall` function gives an assertion failure when a `count` of 0 and a `reqs` array of `MPI_REQUEST_NULL` are provided as arguments. The equivalent `MPI_Waitall` function accepts these as valid inputs - the MPI 3.1 standard specifies `count` is a non-negative integer and that the list may contain null or inactive handles - so I believe this is more likely a bug than undefined behaviour.

Code for reproducing the error and full output are below. Tests were performed on TAMPI v1.0.2 with `--enable-debug-mode` set.

**Sample Program**
```
#include <mpi.h>
#include <TAMPI.h>

int main(int argc, char **argv)
{
  MPI_Request reqs[] = {MPI_REQUEST_NULL};
  int provided;

  MPI_Init_thread(&argc, &argv, MPI_THREAD_MULTIPLE, &provided);
  TAMPI_Iwaitall(0, reqs, MPI_STATUSES_IGNORE);
  MPI_Finalize();

  return 0;
}
```
**Error**
> tampitest.x: ./src/common/RequestManager.hpp:59: static void RequestManager<Lang>::processRequests(util::ArrayView<typename Lang::request_t>, RequestManager<Lang>::status_ptr_t, bool) [with Lang = C; typename Lang::request_t = int; RequestManager<Lang>::status_ptr_t = MPI_Status*]: Assertion `!requests.empty()' failed.
> MPT ERROR: Rank 0(g:0) received signal SIGABRT/SIGIOT(6).

**Comment by kevinsala** [comment]
You are completely right. The MPI standard allows passing zero as the count parameter in MPI_Waitall. In principle, the master branch (c27aaaf655fdca270a6bc48ac9db168240346d13) is now fixed to support a zero parameter in both TAMPI_Iwaitall and MPI_Waitall.

Thank you for reporting this error!
